# .github/workflows/firebase-hosting-merge.yml
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Забираем ваш код
      - uses: actions/checkout@v4

      # 2) Устанавливаем Node.js версии >=20
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      # 3) Устанавливаем зависимости вашего React-проекта
      - name: Install dependencies
        run: npm ci

      # 4) Собираем React-приложение
      - name: Build production bundle
        run: npm run build

      # 5) Деплоим на Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BEACH_RENT_REAL_TIME }}
          channelId: live
          projectId: beach-rent-real-time
